<?php
    $this->title = "My Albums";
    $this->headTitle($this->title);
?>

<p>
    <a class="btn primary" href="
        <?php
        echo $this->url( array( 'controller' => 'index',
                                                'action' => 'add'
        ));            
        ?>
       "
       >
        Add new Album
    </a>
</p>

<table class="zebra-striped">
    <thead>        
        <tr>
            <th>Artist</th>
            <th>Title</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    
    <?php        
            foreach ($this->albums as $aAlbum) :
    ?>
    <tr>
        <td>
            <?php echo $this->escape($aAlbum->artist); ?>
        </td>
        <td>
            <?php echo $this->escape($aAlbum->title); ?>
        </td>
        <td>
            <a class="btn" href=" <?php echo $this->url(array(
                                                'controller' => 'index',
                                                'action' => 'edit',
                                                'id' => $aAlbum->id ));                
                            ?> " >Edit</a>      

            <a class="btn danger" href=" <?php echo $this->url(array(
                                                'controller' => 'index',
                                                'action' => 'delete',
                                                'id' => $aAlbum->id ));                
                            ?> " >Delete</a>
        </td>
    </tr>
    <?php
        endforeach;        
    ?>
</table>